"""empty message

Revision ID: 49c68a0aa852
Revises: 
Create Date: 2020-09-28 22:01:07.214587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c68a0aa852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiqueta',
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_etiqueta')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.Column('apellido', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('encuesta',
    sa.Column('id_encuesta', sa.Integer(), nullable=False),
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_etiqueta'], ['etiqueta.id_etiqueta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_encuesta')
    )
    op.create_table('pregunta',
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('id_encuesta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_encuesta'], ['encuesta.id_encuesta'], ),
    sa.PrimaryKeyConstraint('id_pregunta')
    )
    op.create_table('respuesta',
    sa.Column('id_respuesta', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pregunta'], ['pregunta.id_pregunta'], ),
    sa.PrimaryKeyConstraint('id_respuesta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta')
    op.drop_table('pregunta')
    op.drop_table('encuesta')
    op.drop_table('usuario')
    op.drop_table('etiqueta')
    # ### end Alembic commands ###
